### ISSUE TITLE
Can I share this project in it's current form?

### ISSUE THREAD

**Issue by Koli0842** [Koli0842/LiquidCtlAfterburnerPlugin#1]
Hey @ts-korhonen, @SuspiciousActivity, @jmarucha,

I started this project based on your respectible Afterburner Plugins and FanControl plugins, basically forming an adapter between the interfaces with my very little C# knowledge. I did this to get my Kraken X63 displayed on AIO and reached a point where I'm reasonably happy with it, so thought about sharing it for others.
I don't want to get into plagarism, so I'd like to ask whether you are okay with me sharing this piece of software under it's current terms.

Thanks for your awesome works and reply,
David

**Comment by ts-korhonen** [comment]
Hi! On my behalf it's totally okay! I'm glad to see it used this way 👍

**Comment by jmarucha** [comment]
Dear Koli,

The license for this project explicitly allows that, and I am personally very happy for my code (that I have little time to maintain unfortunately) give raise to more pieces of Free Software.
Consider it strong "YES".

Sent from Nine
________________________________
From: Koli0842 ***@***.***>
Sent: Sunday, 26 March 2023 13:34
To: Koli0842/LiquidCtlAfterBurnerPlugin
Cc: Jan K. Marucha; Mention
Subject: [Koli0842/LiquidCtlAfterBurnerPlugin] Can I share this project in it's current form? (Issue #1)

Hey @ts-korhonen, @SuspiciousActivity, @jmarucha,
I started this project based on your respectible Afterburner Plugins and FanControl plugins, basically forming an adapter between the interfaces with my very little C# knowledge. I did this to get my Kraken X63 displayed on AIO and reached a point where I'm reasonably happy with it, so thought about sharing it for others.
I don't want to get into plagarism, so I'd like to ask whether you are okay with me sharing this piece of software under it's current terms.
Thanks for your awesome works and reply,
David

**Comment by SuspiciousActivity** [comment]
Hey! Yes I'm totally fine with it, love to see my code being used! 😀

**Comment by Koli0842** [comment]
Thanks everyone!
