### ISSUE TITLE
Compatibility with my latest liquidctl fork

### ISSUE THREAD

**Issue by SuspiciousActivity** [Koli0842/LiquidCtlAfterburnerPlugin#2]
Since you are linking to my liquidctl fork, I'd like to remind you that the latest version prints out some additional information which your version of my plugin fork likely doesn't understand yet. I'm not too sure how you could set git up so you can pull from my repo and edit yours as well, but I'm pretty sure my latest liquidctl.exe breaks your dll, because its based on an older version of my plugin fork.
Maybe have a look at the [commits](https://github.com/SuspiciousActivity/FanControl.Liquidctl/commits/master), beginning from `42888bf`.

**Comment by Koli0842** [comment]
Thanks for the heads-up, I will check on this in the following days!

I am also working on a fork for FanControl's LiquidCtl plugin itself, as I had some compatibility issues with my loan Kraken X63 with the upstream version. I've been playing around with building a version with your fork of liquidctl aswell. It's filled with some ugly hacks, including changing the parsed value to object; Corsair PSU in a friend's PC has some string values which result in exceptions. I think I will end up adapting your changes here, as they look a lot better.

I will also try to clean up my branch for the X63 and possibly mainline into jmarucha's plugin, so we don't need to maintain both FanControl plugins.
